# BackPacks+ by CoachL_ck
# Wiki: https://github.com/CoachLuck/BackPacksPlus
# Support: https://discord.gg/HVSNTK3XwN
# PLAYER_HEAD Textures: https://minecraft-heads.com/
# Please do not change Config-Version
Config-Version: 3
Language: "en"
Check-For-Update: true
General:
  BackPackLimiter:
    Enabled: false
    Repeat: 20