# BackPacks+ by CoachL_ck
# Information: https://github.com/CoachLuck/BackPacksPlus
# PLAYER_HEAD Textures: https://minecraft-heads.com/
# Please do not change Config-Version
# To add backpacks just copy a section, for example "BackPacks.Basic" or "BackPacks.Advanced"
# Then paste at the bottom, and rename to "BackPacks.NewName"
# For example:
# BackPacks:
#    Basic:
#      Name: "Some Name"
#      <rest of data>
#    NewName:
#      Name: "Some Name"
#      <rest of data>
Config-Version: 1
Check-For-Update: true
General:
  NestableBackPack: true
  BackPackLimiter:
    Enabled: false
    Repeat: 20
BackPacks:
  Basic:
    Name: "&c&l背包+"
    Title: "&e&l背包"
    Material: "PLAYER_HEAD"
    Texture: "http://textures.minecraft.net/texture/8351e505989838e27287e7afbc7f97e796cab5f3598a76160c131c940d0c5"
    CustomData:
    Lore:
      - "&8&m                                      "
      - " &7点击打开此&d背包"
      - "&8&m                                      "
    Enchanted: true
    Permission: "backpack.basic"
    Size: 18
    Recipe:
      Shape:
        - "LLL"
        - "LCL"
        - "LLL"
      Materials:
        L:
          Material: "LEATHER"
        C:
          Material: "CHEST"
  Advanced:
    Name: "&e&l高级&c&l背包+"
    Title: "&e&l高级&c&l背包"
    Material: "CLOCK"
    Texture: ""
    CustomData:
    Lore:
      - "&8&m                                      "
      - " &7点击打开此&d背包"
      - "&8&m                                      "
    Enchanted: true
    Permission: "backpack.advanced"
    Size: 27
    Recipe:
      Shape:
        - "GGG"
        - "GCG"
        - "GGG"
      Materials:
        G:
          Material: "GOLD_BLOCK"
        C:
          Material: "CHEST"
  Mega:
    Name: "&b&l大型&c&l背包+"
    Title: "&b&l大型&c&l背包"
    Material: "PLAYER_HEAD"
    Texture: "http://textures.minecraft.net/texture/df70fab3246fe027ce0bba885a73c6e82d8ff8f358231e8461f956560cfa58f"
    CustomData:
    Lore:
      - "&8&m                                      "
      - " &7点击打开此&d背包"
      - "&8&m                                      "
    Enchanted: true
    Permission: "backpack.mega"
    Size: 45
    Recipe:
      Shape:
        - "DDD"
        - "DCD"
        - "DDD"
      Materials:
        D:
          Material: "DIAMOND_BLOCK"
        C:
          Material: "CHEST"
